// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_GbIq5EY-Inyf94LxqmNwL_qxKzObZc',
    appId: '1:276981948675:web:b3a916b87f1672c456c936',
    messagingSenderId: '276981948675',
    projectId: 'dindondan-9b3af',
    authDomain: 'dindondan-9b3af.firebaseapp.com',
    databaseURL: 'https://dindondan-9b3af.firebaseio.com',
    storageBucket: 'dindondan-9b3af.appspot.com',
    measurementId: 'G-1XSXJS6L51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCv-qJG-1YHluXBdGMJJlaKCoz8gX1S94',
    appId: '1:276981948675:android:5f4ce0967336661956c936',
    messagingSenderId: '276981948675',
    projectId: 'dindondan-9b3af',
    databaseURL: 'https://dindondan-9b3af.firebaseio.com',
    storageBucket: 'dindondan-9b3af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAllnab5tw7n2t2nFFvUq3GSbvx9ZA9VpA',
    appId: '1:276981948675:ios:40cf089c79d4d9e456c936',
    messagingSenderId: '276981948675',
    projectId: 'dindondan-9b3af',
    databaseURL: 'https://dindondan-9b3af.firebaseio.com',
    storageBucket: 'dindondan-9b3af.appspot.com',
    androidClientId: '276981948675-bb4apa09jfnfc4mrbcmbjlipl6mffun0.apps.googleusercontent.com',
    iosClientId: '276981948675-kbq5guqkrsctnau6h6ehoci4mcl0007g.apps.googleusercontent.com',
    iosBundleId: 'app.dindondan.contapersone',
  );
}
